let f = (x, y) => x;
f("one", "too", "many")

# output:
stdin:2:17
  ╷
2 │ f("one", "too", "many")
  ╵                 ^~~~~~
Error: Unexpected argument. The function takes 2 arguments, but got 3.

stdin:1:16
  ╷
1 │ let f = (x, y) => x;
  ╵                ^~
Note: Function defined here.
